TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: -0.05
  max_vel_theta: 2.0
  min_vel_theta: -2.0
  min_in_place_vel_theta: 0.7
  acc_lim_theta: 0.7
  acc_lim_x: 0.2
  acc_lim_y: 0.0
  holonomic_robot: false
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.1
  meter_scoring: true
  dwa: false
  recovery_behavior_enabled: false
  clearing_rotation_allowed: false
